# syntax=docker/dockerfile:1

# ---- Builder Stage ----
FROM node:20-alpine AS builder
WORKDIR /app
ENV NODE_ENV=production

COPY package.json yarn.lock./
RUN yarn install --frozen-lockfile

COPY . .
RUN yarn build

# ---- Production Stage ----
FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production

RUN addgroup -g 1001 -S nodejs
RUN adduser -S strapi -u 1001 -G nodejs
USER strapi

COPY package.json yarn.lock./
RUN yarn install --production --frozen-lockfile

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/config ./config
COPY --from=builder /app/database ./database
COPY --from=builder /app/public ./public
COPY --from=builder /app/src ./src
COPY --from=builder /app/.strapi ./.strapi

EXPOSE 1337

CMD ["yarn", "start"]